[features]
seeds = false
skip-lint = false

[programs.devnet]
nodus_access = "NodUS11111111111111111111111111111111111111"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node test/anchor-devnet.mjs"
